#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 


name: OpenWrt-CI

on:
  push:
    branches: 
      - main
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:
  build_openwrt:
    
    name: Build OpenWrt firmware

    runs-on: ubuntu-20.04

    steps:
    
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E swapoff -a
          sudo -E rm -f /swapfile
          sudo -E docker image prune -a -f
          sudo -E systemctl stop docker
          sudo -E snap set system refresh.retain=2
          sudo -E apt-get -y purge dotnet* firefox clang* gcc-10* ghc* google* hhvm* llvm* mono* mongo* mysql* openjdk* php* zulu*
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo -E rm -rf /etc/mysql /etc/php /usr/lib/jvm /usr/libexec/docker /usr/local /usr/src/* /var/lib/docker /var/lib/gems /var/lib/mysql /var/lib/snapd /etc/skel /opt/{microsoft,az,hostedtoolcache,cni,mssql-tools,pipx} /usr/share/{az*,dotnet,swift,miniconda,gradle*,java,kotlinc,ri,sbt} /root/{.sbt,.local,.npm}
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          rm -rf ~/{.cargo,.dotnet,.rustup}
          df -h
          
      - name: Download lede
        run: |
          git clone https://github.com/coolsnowwolf/lede
          mv ./lede/* ./
          
      - name: Update feeds
        run: |
          # sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default
          
          sed -i "/helloworld/d" "feeds.conf.default"
          echo "src-git helloworld https://github.com/fw876/helloworld.git" >> "feeds.conf.default"
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # open clash
          # git clone https://github.com/vernesong/OpenClash.git package-temp
          # mv -f package-temp/luci-app-openclash package/lean/
          # rm -rf package-temp

      - name: Custom configure file
        run: |
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          # Device type
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y

          # Gzip
          CONFIG_TARGET_IMAGES_GZIP=y
          
          # 编译UEFI固件:
          # CONFIG_EFI_IMAGES is not set

          # IPv6
          # CONFIG_PACKAGE_dnsmasq_full_dhcpv6 is not set
          # CONFIG_PACKAGE_ipv6helper is not set

          # USB support
          # ONFIG_PACKAGE_kmod-usb-core is not set
          # CONFIG_PACKAGE_kmod-usb3 is not set
          # CONFIG_PACKAGE_kmod-usb-storage is not set
          # CONFIG_PACKAGE_kmod-usb-storage-extras is not set
          # CONFIG_PACKAGE_automount is not set
          
          # Filesystem
          # CONFIG_PACKAGE_kmod-fs-exfat is not set
          # CONFIG_PACKAGE_kmod-fs-ext4 is not set
          # CONFIG_PACKAGE_kmod-fs-ntfs is not set
          # CONFIG_PACKAGE_kmod-fs-nfs is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-common is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-v3 is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-v4 is not set
          # CONFIG_PACKAGE_kmod-fs-ntfs is not set
          # CONFIG_PACKAGE_kmod-fs-squashfs is not set
          
          # APP
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-frps=y
          
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          
          # CONFIG_PACKAGE_luci-app-openclash is not set
          
          # 硬盘休眠
          # CONFIG_PACKAGE_luci-app-hd-idle is not set
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          # CONFIG_PACKAGE_luci-app-aliddns is not set
          # CONFIG_PACKAGE_luci-app-aria2 is not set
          
          #
          # NeteaseMusic
          #
          # CONFIG_DEFAULT_luci-app-unblockmusic is not set
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          # CONFIG_UnblockNeteaseMusic_Go is not set
          # CONFIG_UnblockNeteaseMusic_NodeJS is not set
          # CONFIG_PACKAGE_UnblockNeteaseMusic is not set
          # CONFIG_PACKAGE_UnblockNeteaseMusicGo is not set
          # CONFIG_UnblockNeteaseMusicGo_INCLUDE_GOPROXY is not set
          
          # 京东签到服务
          # CONFIG_PACKAGE_luci-app-jd-dailybonus is not set
          # 网络共享
          # CONFIG_PACKAGE_luci-app-samba is not set
          # IPSec VPN 服务器
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          # 宽带监控
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          # CONFIG_PACKAGE_zerotier is not set
          
          # CONFIG_PACKAGE_luci-app-vlmcsd is not set
          # CONFIG_PACKAGE_vlmcsd is not set

          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_vsftpd is not set
          # CONFIG_PACKAGE_vsftpd-alt is not set
          # CONFIG_PACKAGE_vsftpd-tls is not set
          
          # CONFIG_PACKAGE_luci-app-samba is not set
          # CONFIG_PACKAGE_luci-app-samba4 is not set
          # CONFIG_PACKAGE_samba36-client is not set
          # CONFIG_PACKAGE_samba36-net is not set
          # CONFIG_PACKAGE_samba36-server is not set
          # CONFIG_PACKAGE_samba4-admin is not set
          # CONFIG_PACKAGE_samba4-client is not set
          # CONFIG_PACKAGE_samba4-libs is not set
          # CONFIG_PACKAGE_samba4-server is not set
          # CONFIG_PACKAGE_samba4-utils is not set
          # CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL is not set

          # CONFIG_PACKAGE_luci-app-filetransfer is not set
          
          # UU游戏加速器
          # CONFIG_PACKAGE_luci-app-uugamebooster is not set
          
          # CONFIG_PACKAGE_luci-app-qbittorrent is not set
          # CONFIG_PACKAGE_luci-app-samba is not set
          # CONFIG_PACKAGE_luci-app-mwan3 is not set
          # CONFIG_PACKAGE_luci-app-mwan3helper is not set
          # CONFIG_PACKAGE_luci-app-openvpn is not set
          # CONFIG_PACKAGE_luci-app-openvpn-server is not set
          # CONFIG_PACKAGE_luci-app-samba is not set
          # CONFIG_PACKAGE_luci-app-syncdial is not set
          # CONFIG_PACKAGE_luci-app-ttyd is not set
          # CONFIG_PACKAGE_luci-app-usb-printer is not set
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          # CONFIG_PACKAGE_luci-app-filetransfer is not set
          # CONFIG_PACKAGE_luci-app-arpbind is not set
          # CONFIG_PACKAGE_luci-app-wol is not set
          # CONFIG_PACKAGE_ddns-scripts_aliyun is not set
          # CONFIG_PACKAGE_ddns-scripts_dnspod is not set
          
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          # CONFIG_PACKAGE_luci-app-sfe is not set

          # CONFIG_PACKAGE_libminiupnpc is not set
          # CONFIG_PACKAGE_libnpupnp is not set
          # CONFIG_PACKAGE_libupnp is not set
          # CONFIG_PACKAGE_libupnpp is not set
          # CONFIG_PACKAGE_luci-app-upnp is not set
          # CONFIG_PACKAGE_miniupnpc is not set
          # CONFIG_PACKAGE_miniupnpd is not set
          # CONFIG_PACKAGE_xupnpd is not set

          # 取消编译VMware镜像以及镜像填充
          # CONFIG_TARGET_IMAGES_PAD is not set
          # CONFIG_VMDK_IMAGES is not set
          
          EOF
          
          sed -i 's/^[ \t]*//g' ./.config
          # sed -i 's/192.168.1.1/10.10.10.10/g' package/base-files/files/bin/config_generate
          sed -i "s/hostname='OpenWrt'/hostname='Oht'/g" package/base-files/files/bin/config_generate
          make defconfig
          
      - name:  Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
          
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          
      - name: Generate release tag
        id: tag
        run: |
          tag="x86/64"
          echo "RELEASE_TAG=$tag" >> $GITHUB_OUTPUT
          echo "RELEASE_NAME=$(date +"%Y.%m.%d") for $tag" >> $GITHUB_OUTPUT
          echo "console address: http://192.168.1.1
                default password: password" > release.txt
          echo "RELEASE_SUCCESS=success" >> $GITHUB_OUTPUT
          ls -al ./bin/targets/* >> release.txt

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.RELEASE_SUCCESS == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          name: ${{ steps.tag.outputs.RELEASE_NAME }}
          tag_name: ${{ steps.tag.outputs.RELEASE_TAG }}
          files: ./bin/targets/*img*
          body_path: release.txt
